---
horizon_url: "https://iad2.dreamcompute.com"

auth: {
  auth_url: "https://iad2.dream.io:5000/v2.0",
  username: "stemaf4",
  password: "{{ password }}",
  project_name: "dhc2131831"
}

app_env: {
  target_os: "ubuntu",
  ssh_user: "ubuntu",
  region_name: "RegionOne",
  image_name: "Ubuntu-14.04",
  private_net_name: "",
  validate_certs: False,
  availability_zone: "iad-2",
  flavor_name: "gp1.supersonic",
  public_key_file: "/home/reed/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 10,
  block_device_name: "/dev/vdb"
}
