---
horizon_url: "http://9.30.217.9"

auth: {
  auth_url: "http://9.30.217.9:5000/v3",
  username: "demo",
  password: "{{ password }}",
  domain_name: "default",
  project_name: "demo"
}

app_env: {
  target_os: "ubuntu",
  image_name: "ubuntu-14.04",
  region_name: "RegionOne",
  availability_zone: "nova",
  validate_certs: False,
  ssh_user: "ubuntu",
  private_net_name: "demonet",
  flavor_name: "m1.large",
  public_key_file: "/home/ubuntu/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 2,
  block_device_name: "/dev/vdb",
  wp_latest: "https://wordpress.org/wordpress-4.6.tar.gz"
}
