---
horizon_url: "http://9.30.217.9"

auth: {
  auth_url: "http://9.30.217.9:5000/v3",
  username: "demo",
  password: "{{ password }}",
  domain_name: "default",
  project_name: "demo"
}

app_env: {
  target_os: "ubuntu",
  image_name: "ubuntu-16.04",
  region_name: "RegionOne",
  availability_zone: "nova",
  validate_certs: False,
  ssh_user: "ubuntu",
  private_net_name: "demonet",
  flavor_name: "m1.large",
  public_key_file: "/home/ubuntu/.ssh/interop.pub",
  stack_size: 4,
  volume_size: 2,
  block_device_name: "/dev/vdb",

  # The following section shows how to pre allocate floating IPs for each
  # server. If you wish not to do that, leave them empty.
  ips: {
    apache-1: ["9.30.217.34"],
    apache-2: ["9.30.217.23"],
    balancer: ["9.30.217.28"],
    database: ["9.30.217.35"]
  },

  wp_latest: "http://10.0.10.12/lampstack/wordpress-4.6.1.tar.gz",
  wp_importer: "http://10.0.10.12/lampstack/wordpress-importer.0.6.3.zip"
}
